version: '3'
services:
  names-web:
    image: klaital/names-web:latest
    ports:
      - "8080:8080"
    command: ./names-web
    env_file:
      - ./db.env
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
      - LOG_STYLE=prettyjson
      - MIGRATION_LOCATION=file:///db/migrations
      - DB_DRIVER=mysql
