version: '3'
services:
  names-web:
    image: klaital/names-web:latest
    ports:
      - "8080:8080"
    command: ./names-web
    environment:
      - PORT=8080
      - LOG_LEVEL=debug
      - LOG_STYLE=prettyjson
      - MIGRATION_LOCATION=file:///db/migrations
      - DB_HOST=mysql.abandonedfactory.net
      - DB_NAME=af_names
      - DB_PORT=3306
      - DB_USER=af_namer
      - 'DB_PASS=namer*007'
      - DB_DRIVER=mysql
